server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://userceh-order:8080
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://userceh-delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: product
          uri: http://userceh-product:8080
          predicates:
            - Path=/inventories/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:        
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: order
          uri: http://userceh-order:8080
          predicates:
            - Path=/orders/** 
        - id: delivery
          uri: http://userceh-delivery:8080
          predicates:
            - Path=/deliveries/** 
        - id: product
          uri: http://userceh-product:8080
          predicates:
            - Path=/inventories/** 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
